name: openfe_env
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
dependencies:
  - duecredit<0.10
  - numpy
  - networkx
  - rdkit
  - packaging
  - pip
  - pytest
  - pytest-xdist
  - pytest-cov
  - pytest-rerunfailures
  - pydantic >1
  - pyyaml
  - coverage
  - openff-toolkit>=0.13.0
  - openff-nagl-base >=0.3.3
  - openff-units==0.2.0
  - pint<0.22
  - openff-models>=0.0.5
  - click
  - typing-extensions
  - openmmtools
  - openmmforcefields
  - perses
  - pooch
  - py3dmol
  - plugcli
  - tqdm
  - pygraphviz
  - scikit-learn
  # Issue #443
  - pymbar<4.0
  # docs
  - autodoc-pydantic<2.0
  - pydata-sphinx-theme
  - sphinx-click
  - pip:
    - sphinx-toolbox
    - openff-nagl-models>=0.1.2
    - git+https://github.com/OpenFreeEnergy/gufe@main
    - git+https://github.com/OpenFreeEnergy/Kartograf@main
    - git+https://github.com/OpenFreeEnergy/cinnabar@main
    - git+https://github.com/OpenFreeEnergy/openfe_analysis@main
    - git+https://github.com/OpenFreeEnergy/lomap@main

